Portfolio Contact Form Check-up
frankfembo/my--portfolio pull request #6
Opened 2022-07-12 16:29 UTC by frankfembo

- Add a contact form to portfolio project with input fields
- Include submit button to send user input details to formspree
- Add a footer & mailto: at bottom

2022-07-12 16:52 UTC, topeogunleye requested changes
> # Changes Required 
> ### Hi @frankfembo,
> Nice job, you are almost there.
> 
> ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## (Highlights) Good Points: 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:

>
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please check my inline comments.
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-12 16:52 UTC, topeogunleye commented on index.html
> +                    <textarea class="text-input detail-input" name="text" id="text" cols="23" rows="5" placeholder="Enter text here..." max-length="500" required></textarea>
- [ ] I kindly suggest that you correct your spelling of maxlength HTML attribute

:x: Wrong
`max-length="500"`

:heavy_check_mark: Right
`maxlength="500"`

2022-07-12 16:52 UTC, topeogunleye commented on index.html
>                  <li class="btn-container">
- [ ] I kindly suggest that you add the different button interactions including active (when it's pressed).

![image](https://user-images.githubusercontent.com/52934128/178548917-051dc42c-5bf6-4a46-b635-87e4a6b96a77.png)

the button on the pressed state has the `background: #5E42D7;`
### EXAMPLE:
**for pressed state**
```
button:active {
   background-color: #5E42D7;
}
```

2022-07-13 09:19 UTC, prolajumokeoni approved these changes
Hi @frankfembo, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-13 09:21 UTC, merged